### PR TITLE
CSE-935 optimize dev workflow

### PR DESCRIPTION
**Pull request by voodoods**
**Jira Issue**

https://8select.atlassian.net/browse/CSE-935

**Summary**
- create a `copy2dev.sh` script which copies the current plugin files as a staging build to the plugins folder of your local `docker-shopware` container
- add information for dev workflow to the `README.md`

**Checklist**

- [x] PR title is prefixed with Jira Issue Id - e.g. CSE-42
- [x] Add feature / bug label
- [x] Unit tests for new / changed logic exist OR no logic changes are passing

### CODE REVIEW

**Comment by akleiber** [comment]
this was changed and merged: https://github.com/8select/shopware-plugin-sob/pull/24/files

`__BUCKET__` was renamed to`__SUBDOMAIN__`

**Comment by voodoods** [comment]
changed base + rebased 👍

**Comment by voodoods** [comment]
@akleiber @Wytrykus 
This PR might not be in the current sprint's scope but it would really help to make the development process more convenient and save valuable development time while working on the plugin in the long run. 
If you don't see a need for any big changes, please consider to include this in the current or next sprint, so that we can merge it soon 🙏 😃  thank you

**Comment by Wytrykus** [comment]
If there's no more work to do here, I'd say let's merge and use this productivity tool, what do you think @akleiber ?

**Pull request merged**
